//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapService.KbdapiService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kodekssoap.org/", ConfigurationName="KbdapiService.KBDAPI_docsSoap")]
    public interface KBDAPI_docsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CheckRequestStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfstring")]
        SoapService.KbdapiService.ArrayOfstring CheckRequestStatus(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetCardAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CardAttributes")]
        SoapService.KbdapiService.CardAttributes GetCardAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetClassificatorDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ClassificatorDesc")]
        SoapService.KbdapiService.ClassificatorDesc GetClassificatorDesc(int arg0, int arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentDesc")]
        SoapService.KbdapiService.DocumentDesc GetDocumentDesc(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentAttachmentsDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfAttachmentDesc")]
        SoapService.KbdapiService.ArrayOfAttachmentDesc GetDocumentAttachmentsDesc(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentItems", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentItems")]
        SoapService.KbdapiService.DocumentItems GetDocumentItems(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentLists", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentLists")]
        SoapService.KbdapiService.DocumentLists GetDocumentLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetEditionDesc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="EditionDesc")]
        SoapService.KbdapiService.EditionDesc GetEditionDesc(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetLinkedDocsAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LinkedDocsAttributes")]
        SoapService.KbdapiService.LinkedDocsAttributes GetLinkedDocsAttributes(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetOrgStructure", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfOrganisationDesc")]
        SoapService.KbdapiService.ArrayOfOrganisationDesc GetOrgStructure();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetServiceAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CardAttributes")]
        SoapService.KbdapiService.CardAttributes GetServiceAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetStatusSettings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StatusSettings")]
        SoapService.KbdapiService.StatusSettings GetStatusSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/AddAttachment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string AddAttachment(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CreateEdition", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string CreateEdition(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CreateCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string CreateCard(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/DeleteAttachments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string DeleteAttachments(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/EditAttachments", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string EditAttachments(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/EditCard", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string EditCard(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/RemoveDocument", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string RemoveDocument(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDocx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDocx(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKDoc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKDoc(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKXml", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKXml(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetText", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetText(int arg0, string arg1, string arg2, string arg3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDefaultPdfViewer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDefaultPdfViewer(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDraftModeOff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDraftModeOff(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDraftModeOn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDraftModeOn(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksAttachModeOff", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksAttachModeOff(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksAttachModeOn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksAttachModeOn(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksStatus(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetOrganisation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetOrganisation(int arg0, string arg1, int arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetServiceAttributes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetServiceAttributes(int arg0, string arg1, string arg2, string arg3);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ArrayOfstring : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] stringField;
        
        /// <remarks/>
        public string[] @string {
            get {
                return this.stringField;
            }
            set {
                this.stringField = value;
                this.RaisePropertyChanged("string");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class StatusSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int statusAttrField;
        
        private ArrayOfClassificatorValue actualField;
        
        private ArrayOfClassificatorValue inactiveField;
        
        private ArrayOfClassificatorValue specialField;
        
        private ArrayOfClassificatorValue substitutiveField;
        
        private ArrayOfClassificatorValue substitutableField;
        
        private ArrayOfClassificatorValue cancellingField;
        
        private ArrayOfClassificatorValue cancellableField;
        
        private ArrayOfClassificatorValue changingField;
        
        private ArrayOfClassificatorValue changeableField;
        
        /// <remarks/>
        public int statusAttr {
            get {
                return this.statusAttrField;
            }
            set {
                this.statusAttrField = value;
                this.RaisePropertyChanged("statusAttr");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue actual {
            get {
                return this.actualField;
            }
            set {
                this.actualField = value;
                this.RaisePropertyChanged("actual");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue inactive {
            get {
                return this.inactiveField;
            }
            set {
                this.inactiveField = value;
                this.RaisePropertyChanged("inactive");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue special {
            get {
                return this.specialField;
            }
            set {
                this.specialField = value;
                this.RaisePropertyChanged("special");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue substitutive {
            get {
                return this.substitutiveField;
            }
            set {
                this.substitutiveField = value;
                this.RaisePropertyChanged("substitutive");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue substitutable {
            get {
                return this.substitutableField;
            }
            set {
                this.substitutableField = value;
                this.RaisePropertyChanged("substitutable");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue cancelling {
            get {
                return this.cancellingField;
            }
            set {
                this.cancellingField = value;
                this.RaisePropertyChanged("cancelling");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue cancellable {
            get {
                return this.cancellableField;
            }
            set {
                this.cancellableField = value;
                this.RaisePropertyChanged("cancellable");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue changing {
            get {
                return this.changingField;
            }
            set {
                this.changingField = value;
                this.RaisePropertyChanged("changing");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue changeable {
            get {
                return this.changeableField;
            }
            set {
                this.changeableField = value;
                this.RaisePropertyChanged("changeable");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ArrayOfClassificatorValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ClassificatorValue[] item_ClassificatorValueField;
        
        /// <remarks/>
        public ClassificatorValue[] item_ClassificatorValue {
            get {
                return this.item_ClassificatorValueField;
            }
            set {
                this.item_ClassificatorValueField = value;
                this.RaisePropertyChanged("item_ClassificatorValue");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ClassificatorValue : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int oidField;
        
        private string nameField;
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class OrganisationDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private int oidField;
        
        private int parentOidField;
        
        private bool parentOidFieldSpecified;
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public int parentOid {
            get {
                return this.parentOidField;
            }
            set {
                this.parentOidField = value;
                this.RaisePropertyChanged("parentOid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool parentOidSpecified {
            get {
                return this.parentOidFieldSpecified;
            }
            set {
                this.parentOidFieldSpecified = value;
                this.RaisePropertyChanged("parentOidSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ArrayOfOrganisationDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private OrganisationDesc[] item_OrganisationDescField;
        
        /// <remarks/>
        public OrganisationDesc[] item_OrganisationDesc {
            get {
                return this.item_OrganisationDescField;
            }
            set {
                this.item_OrganisationDescField = value;
                this.RaisePropertyChanged("item_OrganisationDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class LinkedDocsAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int activeAttrNumField;
        
        private int passiveAttrNumField;
        
        /// <remarks/>
        public int activeAttrNum {
            get {
                return this.activeAttrNumField;
            }
            set {
                this.activeAttrNumField = value;
                this.RaisePropertyChanged("activeAttrNum");
            }
        }
        
        /// <remarks/>
        public int passiveAttrNum {
            get {
                return this.passiveAttrNumField;
            }
            set {
                this.passiveAttrNumField = value;
                this.RaisePropertyChanged("passiveAttrNum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class EditionDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int oidField;
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class DocumentList : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private int oidField;
        
        private string nameField;
        
        private string accessTypeField;
        
        private string additionalInfoField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        public string accessType {
            get {
                return this.accessTypeField;
            }
            set {
                this.accessTypeField = value;
                this.RaisePropertyChanged("accessType");
            }
        }
        
        /// <remarks/>
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                this.additionalInfoField = value;
                this.RaisePropertyChanged("additionalInfo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class DocumentLists : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DocumentList[] item_DocumentListField;
        
        /// <remarks/>
        public DocumentList[] item_DocumentList {
            get {
                return this.item_DocumentListField;
            }
            set {
                this.item_DocumentListField = value;
                this.RaisePropertyChanged("item_DocumentList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class AttachmentItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string fileNameField;
        
        private string base64strField;
        
        private int isScancopyField;
        
        /// <remarks/>
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
                this.RaisePropertyChanged("fileName");
            }
        }
        
        /// <remarks/>
        public string base64str {
            get {
                return this.base64strField;
            }
            set {
                this.base64strField = value;
                this.RaisePropertyChanged("base64str");
            }
        }
        
        /// <remarks/>
        public int isScancopy {
            get {
                return this.isScancopyField;
            }
            set {
                this.isScancopyField = value;
                this.RaisePropertyChanged("isScancopy");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ArrayOfAttachmentItem : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttachmentItem[] item_AttachmentItemField;
        
        /// <remarks/>
        public AttachmentItem[] item_AttachmentItem {
            get {
                return this.item_AttachmentItemField;
            }
            set {
                this.item_AttachmentItemField = value;
                this.RaisePropertyChanged("item_AttachmentItem");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class DocumentItems : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string textField;
        
        private string notesField;
        
        private ArrayOfAttachmentItem attachmentsField;
        
        /// <remarks/>
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        public string notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
                this.RaisePropertyChanged("notes");
            }
        }
        
        /// <remarks/>
        public ArrayOfAttachmentItem attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("attachments");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class AttachmentDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int oidField;
        
        private string filenameField;
        
        private string descriptionField;
        
        private string modifiedField;
        
        private int isScanCopyField;
        
        private int isDownloadableField;
        
        private int isConvertableField;
        
        private int isConvertedField;
        
        private int isEncryptedField;
        
        private int hasIndexField;
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                this.filenameField = value;
                this.RaisePropertyChanged("filename");
            }
        }
        
        /// <remarks/>
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("description");
            }
        }
        
        /// <remarks/>
        public string modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
                this.RaisePropertyChanged("modified");
            }
        }
        
        /// <remarks/>
        public int isScanCopy {
            get {
                return this.isScanCopyField;
            }
            set {
                this.isScanCopyField = value;
                this.RaisePropertyChanged("isScanCopy");
            }
        }
        
        /// <remarks/>
        public int isDownloadable {
            get {
                return this.isDownloadableField;
            }
            set {
                this.isDownloadableField = value;
                this.RaisePropertyChanged("isDownloadable");
            }
        }
        
        /// <remarks/>
        public int isConvertable {
            get {
                return this.isConvertableField;
            }
            set {
                this.isConvertableField = value;
                this.RaisePropertyChanged("isConvertable");
            }
        }
        
        /// <remarks/>
        public int isConverted {
            get {
                return this.isConvertedField;
            }
            set {
                this.isConvertedField = value;
                this.RaisePropertyChanged("isConverted");
            }
        }
        
        /// <remarks/>
        public int isEncrypted {
            get {
                return this.isEncryptedField;
            }
            set {
                this.isEncryptedField = value;
                this.RaisePropertyChanged("isEncrypted");
            }
        }
        
        /// <remarks/>
        public int hasIndex {
            get {
                return this.hasIndexField;
            }
            set {
                this.hasIndexField = value;
                this.RaisePropertyChanged("hasIndex");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ArrayOfAttachmentDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private AttachmentDesc[] item_AttachmentDescField;
        
        /// <remarks/>
        public AttachmentDesc[] item_AttachmentDesc {
            get {
                return this.item_AttachmentDescField;
            }
            set {
                this.item_AttachmentDescField = value;
                this.RaisePropertyChanged("item_AttachmentDesc");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class DocumentDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int oidField;
        
        private string nameField;
        
        /// <remarks/>
        public int oid {
            get {
                return this.oidField;
            }
            set {
                this.oidField = value;
                this.RaisePropertyChanged("oid");
            }
        }
        
        /// <remarks/>
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class ClassificatorDesc : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string typeField;
        
        private ArrayOfClassificatorValue valuesField;
        
        /// <remarks/>
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        public ArrayOfClassificatorValue values {
            get {
                return this.valuesField;
            }
            set {
                this.valuesField = value;
                this.RaisePropertyChanged("values");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class CardAttribute : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int attrnumField;
        
        private int typeField;
        
        private string titleField;
        
        /// <remarks/>
        public int attrnum {
            get {
                return this.attrnumField;
            }
            set {
                this.attrnumField = value;
                this.RaisePropertyChanged("attrnum");
            }
        }
        
        /// <remarks/>
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
                this.RaisePropertyChanged("title");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://kodekssoap.org/")]
    public partial class CardAttributes : object, System.ComponentModel.INotifyPropertyChanged {
        
        private CardAttribute[] item_CardAttributeField;
        
        /// <remarks/>
        public CardAttribute[] item_CardAttribute {
            get {
                return this.item_CardAttributeField;
            }
            set {
                this.item_CardAttributeField = value;
                this.RaisePropertyChanged("item_CardAttribute");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KBDAPI_docsSoapChannel : SoapService.KbdapiService.KBDAPI_docsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KBDAPI_docsSoapClient : System.ServiceModel.ClientBase<SoapService.KbdapiService.KBDAPI_docsSoap>, SoapService.KbdapiService.KBDAPI_docsSoap {
        
        public KBDAPI_docsSoapClient() {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KBDAPI_docsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SoapService.KbdapiService.ArrayOfstring CheckRequestStatus(string arg0) {
            return base.Channel.CheckRequestStatus(arg0);
        }
        
        public SoapService.KbdapiService.CardAttributes GetCardAttributes() {
            return base.Channel.GetCardAttributes();
        }
        
        public SoapService.KbdapiService.ClassificatorDesc GetClassificatorDesc(int arg0, int arg1) {
            return base.Channel.GetClassificatorDesc(arg0, arg1);
        }
        
        public SoapService.KbdapiService.DocumentDesc GetDocumentDesc(string arg0) {
            return base.Channel.GetDocumentDesc(arg0);
        }
        
        public SoapService.KbdapiService.ArrayOfAttachmentDesc GetDocumentAttachmentsDesc(int arg0, string arg1, string arg2) {
            return base.Channel.GetDocumentAttachmentsDesc(arg0, arg1, arg2);
        }
        
        public SoapService.KbdapiService.DocumentItems GetDocumentItems(int arg0, string arg1, string arg2) {
            return base.Channel.GetDocumentItems(arg0, arg1, arg2);
        }
        
        public SoapService.KbdapiService.DocumentLists GetDocumentLists() {
            return base.Channel.GetDocumentLists();
        }
        
        public SoapService.KbdapiService.EditionDesc GetEditionDesc(string arg0) {
            return base.Channel.GetEditionDesc(arg0);
        }
        
        public SoapService.KbdapiService.LinkedDocsAttributes GetLinkedDocsAttributes(string arg0) {
            return base.Channel.GetLinkedDocsAttributes(arg0);
        }
        
        public SoapService.KbdapiService.ArrayOfOrganisationDesc GetOrgStructure() {
            return base.Channel.GetOrgStructure();
        }
        
        public SoapService.KbdapiService.CardAttributes GetServiceAttributes() {
            return base.Channel.GetServiceAttributes();
        }
        
        public SoapService.KbdapiService.StatusSettings GetStatusSettings() {
            return base.Channel.GetStatusSettings();
        }
        
        public string AddAttachment(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9) {
            return base.Channel.AddAttachment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
        }
        
        public string CreateEdition(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            return base.Channel.CreateEdition(arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        public string CreateCard(string arg0, string arg1) {
            return base.Channel.CreateCard(arg0, arg1);
        }
        
        public string DeleteAttachments(int arg0, string arg1) {
            return base.Channel.DeleteAttachments(arg0, arg1);
        }
        
        public string EditAttachments(string arg0) {
            return base.Channel.EditAttachments(arg0);
        }
        
        public string EditCard(int arg0, string arg1, string arg2) {
            return base.Channel.EditCard(arg0, arg1, arg2);
        }
        
        public string RemoveDocument(int arg0, string arg1) {
            return base.Channel.RemoveDocument(arg0, arg1);
        }
        
        public string SetDocx(int arg0, string arg1, string arg2) {
            return base.Channel.SetDocx(arg0, arg1, arg2);
        }
        
        public string SetKDoc(int arg0, string arg1, string arg2) {
            return base.Channel.SetKDoc(arg0, arg1, arg2);
        }
        
        public string SetKXml(int arg0, string arg1, string arg2) {
            return base.Channel.SetKXml(arg0, arg1, arg2);
        }
        
        public string SetText(int arg0, string arg1, string arg2, string arg3) {
            return base.Channel.SetText(arg0, arg1, arg2, arg3);
        }
        
        public string SetDefaultPdfViewer(int arg0, string arg1, string arg2) {
            return base.Channel.SetDefaultPdfViewer(arg0, arg1, arg2);
        }
        
        public string SetDraftModeOff(int arg0, string arg1) {
            return base.Channel.SetDraftModeOff(arg0, arg1);
        }
        
        public string SetDraftModeOn(int arg0, string arg1) {
            return base.Channel.SetDraftModeOn(arg0, arg1);
        }
        
        public string SetKodeksAttachModeOff(int arg0, string arg1) {
            return base.Channel.SetKodeksAttachModeOff(arg0, arg1);
        }
        
        public string SetKodeksAttachModeOn(int arg0, string arg1) {
            return base.Channel.SetKodeksAttachModeOn(arg0, arg1);
        }
        
        public string SetKodeksStatus(int arg0, string arg1, string arg2) {
            return base.Channel.SetKodeksStatus(arg0, arg1, arg2);
        }
        
        public string SetOrganisation(int arg0, string arg1, int arg2) {
            return base.Channel.SetOrganisation(arg0, arg1, arg2);
        }
        
        public string SetServiceAttributes(int arg0, string arg1, string arg2, string arg3) {
            return base.Channel.SetServiceAttributes(arg0, arg1, arg2, arg3);
        }
    }
}
