//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUNTDLite.DocsSoapService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfstring", Namespace="http://kodekssoap.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfstring : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfCardAttribute", Namespace="http://kodekssoap.org/", ItemName="item_CardAttribute")]
    [System.SerializableAttribute()]
    public class ArrayOfCardAttribute : System.Collections.Generic.List<SUNTDLite.DocsSoapService.CardAttribute> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CardAttribute", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class CardAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long attrnumField;
        
        private string typeField;
        
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long attrnum {
            get {
                return this.attrnumField;
            }
            set {
                if ((this.attrnumField.Equals(value) != true)) {
                    this.attrnumField = value;
                    this.RaisePropertyChanged("attrnum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificatorDesc", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class ClassificatorDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string typeField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue valuesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue values {
            get {
                return this.valuesField;
            }
            set {
                if ((object.ReferenceEquals(this.valuesField, value) != true)) {
                    this.valuesField = value;
                    this.RaisePropertyChanged("values");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfClassificatorValue", Namespace="http://kodekssoap.org/", ItemName="item_ClassificatorValue")]
    [System.SerializableAttribute()]
    public class ArrayOfClassificatorValue : System.Collections.Generic.List<SUNTDLite.DocsSoapService.ClassificatorValue> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClassificatorValue", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class ClassificatorValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int oidField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentDesc", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class DocumentDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long oidField;
        
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAttachmentDesc", Namespace="http://kodekssoap.org/", ItemName="item_AttachmentDesc")]
    [System.SerializableAttribute()]
    public class ArrayOfAttachmentDesc : System.Collections.Generic.List<SUNTDLite.DocsSoapService.AttachmentDesc> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentDesc", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class AttachmentDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int oidField;
        
        private string filenameField;
        
        private string descriptionField;
        
        private string modifiedField;
        
        private int isScanCopyField;
        
        private int isDownloadableField;
        
        private int isConvertableField;
        
        private int isConvertedField;
        
        private int isEncryptedField;
        
        private int hasIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((object.ReferenceEquals(this.filenameField, value) != true)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string modified {
            get {
                return this.modifiedField;
            }
            set {
                if ((object.ReferenceEquals(this.modifiedField, value) != true)) {
                    this.modifiedField = value;
                    this.RaisePropertyChanged("modified");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int isScanCopy {
            get {
                return this.isScanCopyField;
            }
            set {
                if ((this.isScanCopyField.Equals(value) != true)) {
                    this.isScanCopyField = value;
                    this.RaisePropertyChanged("isScanCopy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int isDownloadable {
            get {
                return this.isDownloadableField;
            }
            set {
                if ((this.isDownloadableField.Equals(value) != true)) {
                    this.isDownloadableField = value;
                    this.RaisePropertyChanged("isDownloadable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int isConvertable {
            get {
                return this.isConvertableField;
            }
            set {
                if ((this.isConvertableField.Equals(value) != true)) {
                    this.isConvertableField = value;
                    this.RaisePropertyChanged("isConvertable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int isConverted {
            get {
                return this.isConvertedField;
            }
            set {
                if ((this.isConvertedField.Equals(value) != true)) {
                    this.isConvertedField = value;
                    this.RaisePropertyChanged("isConverted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int isEncrypted {
            get {
                return this.isEncryptedField;
            }
            set {
                if ((this.isEncryptedField.Equals(value) != true)) {
                    this.isEncryptedField = value;
                    this.RaisePropertyChanged("isEncrypted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int hasIndex {
            get {
                return this.hasIndexField;
            }
            set {
                if ((this.hasIndexField.Equals(value) != true)) {
                    this.hasIndexField = value;
                    this.RaisePropertyChanged("hasIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentItems", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.AttachmentDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.AttachmentItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.CardAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfCardAttribute))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ClassificatorValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfClassificatorValue))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ClassificatorDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.DocumentDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfAttachmentItem))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.DocumentList))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.DocumentLists))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.EditionDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.LinkedDocsAttributes))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.OrganisationDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.StatusSettings))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfstring))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfAttachmentDesc))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(SUNTDLite.DocsSoapService.ArrayOfOrganisationDesc))]
    public partial class DocumentItems : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object notesField;
        
        private SUNTDLite.DocsSoapService.ArrayOfAttachmentItem attachmentsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public object text {
            get {
                return this.textField;
            }
            set {
                if ((object.ReferenceEquals(this.textField, value) != true)) {
                    this.textField = value;
                    this.RaisePropertyChanged("text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public object notes {
            get {
                return this.notesField;
            }
            set {
                if ((object.ReferenceEquals(this.notesField, value) != true)) {
                    this.notesField = value;
                    this.RaisePropertyChanged("notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public SUNTDLite.DocsSoapService.ArrayOfAttachmentItem attachments {
            get {
                return this.attachmentsField;
            }
            set {
                if ((object.ReferenceEquals(this.attachmentsField, value) != true)) {
                    this.attachmentsField = value;
                    this.RaisePropertyChanged("attachments");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AttachmentItem", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class AttachmentItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string fileNameField;
        
        private string base64strField;
        
        private int isScancopyField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.fileNameField, value) != true)) {
                    this.fileNameField = value;
                    this.RaisePropertyChanged("fileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public string base64str {
            get {
                return this.base64strField;
            }
            set {
                if ((object.ReferenceEquals(this.base64strField, value) != true)) {
                    this.base64strField = value;
                    this.RaisePropertyChanged("base64str");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int isScancopy {
            get {
                return this.isScancopyField;
            }
            set {
                if ((this.isScancopyField.Equals(value) != true)) {
                    this.isScancopyField = value;
                    this.RaisePropertyChanged("isScancopy");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAttachmentItem", Namespace="http://kodekssoap.org/", ItemName="item_AttachmentItem")]
    [System.SerializableAttribute()]
    public class ArrayOfAttachmentItem : System.Collections.Generic.List<SUNTDLite.DocsSoapService.AttachmentItem> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DocumentList", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class DocumentList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string typeField;
        
        private int oidField;
        
        private string nameField;
        
        private string accessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additionalInfoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public string accessType {
            get {
                return this.accessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.accessTypeField, value) != true)) {
                    this.accessTypeField = value;
                    this.RaisePropertyChanged("accessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string additionalInfo {
            get {
                return this.additionalInfoField;
            }
            set {
                if ((object.ReferenceEquals(this.additionalInfoField, value) != true)) {
                    this.additionalInfoField = value;
                    this.RaisePropertyChanged("additionalInfo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="DocumentLists", Namespace="http://kodekssoap.org/", ItemName="item_DocumentList")]
    [System.SerializableAttribute()]
    public class DocumentLists : System.Collections.Generic.List<SUNTDLite.DocsSoapService.DocumentList> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EditionDesc", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class EditionDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int oidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LinkedDocsAttributes", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class LinkedDocsAttributes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int activeAttrNumField;
        
        private int passiveAttrNumField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int activeAttrNum {
            get {
                return this.activeAttrNumField;
            }
            set {
                if ((this.activeAttrNumField.Equals(value) != true)) {
                    this.activeAttrNumField = value;
                    this.RaisePropertyChanged("activeAttrNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int passiveAttrNum {
            get {
                return this.passiveAttrNumField;
            }
            set {
                if ((this.passiveAttrNumField.Equals(value) != true)) {
                    this.passiveAttrNumField = value;
                    this.RaisePropertyChanged("passiveAttrNum");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OrganisationDesc", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class OrganisationDesc : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string nameField;
        
        private int oidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int parentOidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int oid {
            get {
                return this.oidField;
            }
            set {
                if ((this.oidField.Equals(value) != true)) {
                    this.oidField = value;
                    this.RaisePropertyChanged("oid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parentOid {
            get {
                return this.parentOidField;
            }
            set {
                if ((this.parentOidField.Equals(value) != true)) {
                    this.parentOidField = value;
                    this.RaisePropertyChanged("parentOid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusSettings", Namespace="http://kodekssoap.org/")]
    [System.SerializableAttribute()]
    public partial class StatusSettings : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int statusAttrField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue actualField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue inactiveField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue specialField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue substitutiveField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue substitutableField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue cancellingField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue cancellableField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue changingField;
        
        private SUNTDLite.DocsSoapService.ArrayOfClassificatorValue changeableField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int statusAttr {
            get {
                return this.statusAttrField;
            }
            set {
                if ((this.statusAttrField.Equals(value) != true)) {
                    this.statusAttrField = value;
                    this.RaisePropertyChanged("statusAttr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue actual {
            get {
                return this.actualField;
            }
            set {
                if ((object.ReferenceEquals(this.actualField, value) != true)) {
                    this.actualField = value;
                    this.RaisePropertyChanged("actual");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=2)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue inactive {
            get {
                return this.inactiveField;
            }
            set {
                if ((object.ReferenceEquals(this.inactiveField, value) != true)) {
                    this.inactiveField = value;
                    this.RaisePropertyChanged("inactive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=3)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue special {
            get {
                return this.specialField;
            }
            set {
                if ((object.ReferenceEquals(this.specialField, value) != true)) {
                    this.specialField = value;
                    this.RaisePropertyChanged("special");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=4)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue substitutive {
            get {
                return this.substitutiveField;
            }
            set {
                if ((object.ReferenceEquals(this.substitutiveField, value) != true)) {
                    this.substitutiveField = value;
                    this.RaisePropertyChanged("substitutive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue substitutable {
            get {
                return this.substitutableField;
            }
            set {
                if ((object.ReferenceEquals(this.substitutableField, value) != true)) {
                    this.substitutableField = value;
                    this.RaisePropertyChanged("substitutable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=6)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue cancelling {
            get {
                return this.cancellingField;
            }
            set {
                if ((object.ReferenceEquals(this.cancellingField, value) != true)) {
                    this.cancellingField = value;
                    this.RaisePropertyChanged("cancelling");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=7)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue cancellable {
            get {
                return this.cancellableField;
            }
            set {
                if ((object.ReferenceEquals(this.cancellableField, value) != true)) {
                    this.cancellableField = value;
                    this.RaisePropertyChanged("cancellable");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=8)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue changing {
            get {
                return this.changingField;
            }
            set {
                if ((object.ReferenceEquals(this.changingField, value) != true)) {
                    this.changingField = value;
                    this.RaisePropertyChanged("changing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=9)]
        public SUNTDLite.DocsSoapService.ArrayOfClassificatorValue changeable {
            get {
                return this.changeableField;
            }
            set {
                if ((object.ReferenceEquals(this.changeableField, value) != true)) {
                    this.changeableField = value;
                    this.RaisePropertyChanged("changeable");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfOrganisationDesc", Namespace="http://kodekssoap.org/", ItemName="item_OrganisationDesc")]
    [System.SerializableAttribute()]
    public class ArrayOfOrganisationDesc : System.Collections.Generic.List<SUNTDLite.DocsSoapService.OrganisationDesc> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://kodekssoap.org/", ConfigurationName="DocsSoapService.KBDAPI_docsSoap")]
    public interface KBDAPI_docsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CheckRequestStatus", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfstring")]
        SUNTDLite.DocsSoapService.ArrayOfstring CheckRequestStatus(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetCardAttributes", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="CardAttributes")]
        SUNTDLite.DocsSoapService.ArrayOfCardAttribute GetCardAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetClassificatorDesc", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ClassificatorDesc")]
        SUNTDLite.DocsSoapService.ClassificatorDesc GetClassificatorDesc(int arg0, int arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentDesc", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentDesc")]
        SUNTDLite.DocsSoapService.DocumentDesc GetDocumentDesc(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentAttachmentsDesc", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfAttachmentDesc")]
        SUNTDLite.DocsSoapService.ArrayOfAttachmentDesc GetDocumentAttachmentsDesc(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentItems", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentItems")]
        SUNTDLite.DocsSoapService.DocumentItems GetDocumentItems(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetDocumentLists", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DocumentLists")]
        SUNTDLite.DocsSoapService.DocumentLists GetDocumentLists();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetEditionDesc", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="EditionDesc")]
        SUNTDLite.DocsSoapService.EditionDesc GetEditionDesc(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetLinkedDocsAttributes", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="LinkedDocsAttributes")]
        SUNTDLite.DocsSoapService.LinkedDocsAttributes GetLinkedDocsAttributes(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetOrgStructure", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfOrganisationDesc")]
        SUNTDLite.DocsSoapService.ArrayOfOrganisationDesc GetOrgStructure();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetServiceAttributes", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ArrayOfCardAttribute")]
        SUNTDLite.DocsSoapService.ArrayOfCardAttribute GetServiceAttributes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/GetStatusSettings", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="StatusSettings")]
        SUNTDLite.DocsSoapService.StatusSettings GetStatusSettings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/AddAttachment", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string AddAttachment(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CreateEdition", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string CreateEdition(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/CreateCard", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string CreateCard(string arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/DeleteAttachments", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string DeleteAttachments(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/EditAttachments", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string EditAttachments(string arg0);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/EditCard", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string EditCard(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/RemoveDocument", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string RemoveDocument(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDocx", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDocx(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKDoc", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKDoc(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKXml", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKXml(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetText", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetText(int arg0, string arg1, string arg2, string arg3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDefaultPdfViewer", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDefaultPdfViewer(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDraftModeOff", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDraftModeOff(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetDraftModeOn", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetDraftModeOn(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksAttachModeOff", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksAttachModeOff(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksAttachModeOn", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksAttachModeOn(int arg0, string arg1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetKodeksStatus", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetKodeksStatus(int arg0, string arg1, string arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetOrganisation", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetOrganisation(int arg0, string arg1, int arg2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://kodekssoap.org/SetServiceAttributes", ReplyAction="*")]
        [System.ServiceModel.DataContractFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string SetServiceAttributes(int arg0, string arg1, string arg2, string arg3);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface KBDAPI_docsSoapChannel : SUNTDLite.DocsSoapService.KBDAPI_docsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KBDAPI_docsSoapClient : System.ServiceModel.ClientBase<SUNTDLite.DocsSoapService.KBDAPI_docsSoap>, SUNTDLite.DocsSoapService.KBDAPI_docsSoap {
        
        public KBDAPI_docsSoapClient() {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KBDAPI_docsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KBDAPI_docsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SUNTDLite.DocsSoapService.ArrayOfstring CheckRequestStatus(string arg0) {
            return base.Channel.CheckRequestStatus(arg0);
        }
        
        public SUNTDLite.DocsSoapService.ArrayOfCardAttribute GetCardAttributes() {
            return base.Channel.GetCardAttributes();
        }
        
        public SUNTDLite.DocsSoapService.ClassificatorDesc GetClassificatorDesc(int arg0, int arg1) {
            return base.Channel.GetClassificatorDesc(arg0, arg1);
        }
        
        public SUNTDLite.DocsSoapService.DocumentDesc GetDocumentDesc(string arg0) {
            return base.Channel.GetDocumentDesc(arg0);
        }
        
        public SUNTDLite.DocsSoapService.ArrayOfAttachmentDesc GetDocumentAttachmentsDesc(int arg0, string arg1, string arg2) {
            return base.Channel.GetDocumentAttachmentsDesc(arg0, arg1, arg2);
        }
        
        public SUNTDLite.DocsSoapService.DocumentItems GetDocumentItems(int arg0, string arg1, string arg2) {
            return base.Channel.GetDocumentItems(arg0, arg1, arg2);
        }
        
        public SUNTDLite.DocsSoapService.DocumentLists GetDocumentLists() {
            return base.Channel.GetDocumentLists();
        }
        
        public SUNTDLite.DocsSoapService.EditionDesc GetEditionDesc(string arg0) {
            return base.Channel.GetEditionDesc(arg0);
        }
        
        public SUNTDLite.DocsSoapService.LinkedDocsAttributes GetLinkedDocsAttributes(string arg0) {
            return base.Channel.GetLinkedDocsAttributes(arg0);
        }
        
        public SUNTDLite.DocsSoapService.ArrayOfOrganisationDesc GetOrgStructure() {
            return base.Channel.GetOrgStructure();
        }
        
        public SUNTDLite.DocsSoapService.ArrayOfCardAttribute GetServiceAttributes() {
            return base.Channel.GetServiceAttributes();
        }
        
        public SUNTDLite.DocsSoapService.StatusSettings GetStatusSettings() {
            return base.Channel.GetStatusSettings();
        }
        
        public string AddAttachment(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5, int arg6, int arg7, int arg8, int arg9) {
            return base.Channel.AddAttachment(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
        }
        
        public string CreateEdition(int arg0, string arg1, string arg2, string arg3, int arg4, int arg5) {
            return base.Channel.CreateEdition(arg0, arg1, arg2, arg3, arg4, arg5);
        }
        
        public string CreateCard(string arg0, string arg1) {
            return base.Channel.CreateCard(arg0, arg1);
        }
        
        public string DeleteAttachments(int arg0, string arg1) {
            return base.Channel.DeleteAttachments(arg0, arg1);
        }
        
        public string EditAttachments(string arg0) {
            return base.Channel.EditAttachments(arg0);
        }
        
        public string EditCard(int arg0, string arg1, string arg2) {
            return base.Channel.EditCard(arg0, arg1, arg2);
        }
        
        public string RemoveDocument(int arg0, string arg1) {
            return base.Channel.RemoveDocument(arg0, arg1);
        }
        
        public string SetDocx(int arg0, string arg1, string arg2) {
            return base.Channel.SetDocx(arg0, arg1, arg2);
        }
        
        public string SetKDoc(int arg0, string arg1, string arg2) {
            return base.Channel.SetKDoc(arg0, arg1, arg2);
        }
        
        public string SetKXml(int arg0, string arg1, string arg2) {
            return base.Channel.SetKXml(arg0, arg1, arg2);
        }
        
        public string SetText(int arg0, string arg1, string arg2, string arg3) {
            return base.Channel.SetText(arg0, arg1, arg2, arg3);
        }
        
        public string SetDefaultPdfViewer(int arg0, string arg1, string arg2) {
            return base.Channel.SetDefaultPdfViewer(arg0, arg1, arg2);
        }
        
        public string SetDraftModeOff(int arg0, string arg1) {
            return base.Channel.SetDraftModeOff(arg0, arg1);
        }
        
        public string SetDraftModeOn(int arg0, string arg1) {
            return base.Channel.SetDraftModeOn(arg0, arg1);
        }
        
        public string SetKodeksAttachModeOff(int arg0, string arg1) {
            return base.Channel.SetKodeksAttachModeOff(arg0, arg1);
        }
        
        public string SetKodeksAttachModeOn(int arg0, string arg1) {
            return base.Channel.SetKodeksAttachModeOn(arg0, arg1);
        }
        
        public string SetKodeksStatus(int arg0, string arg1, string arg2) {
            return base.Channel.SetKodeksStatus(arg0, arg1, arg2);
        }
        
        public string SetOrganisation(int arg0, string arg1, int arg2) {
            return base.Channel.SetOrganisation(arg0, arg1, arg2);
        }
        
        public string SetServiceAttributes(int arg0, string arg1, string arg2, string arg3) {
            return base.Channel.SetServiceAttributes(arg0, arg1, arg2, arg3);
        }
    }
}
